### ISSUE TITLE
SagaDataDocument has been changed to internal class in Rebus.RavenDb 4.0.0 and its blocking update from 3.0.0

### ISSUE THREAD

**Issue by b2yq** [rebus-org/Rebus.RavenDb#4]
I am trying to update Rebus.RavenDb project from 3.0.0 to 4.0.0 and i have found one problem, right now SagaDataDocument is an internal class, previously it was public and in project that i am working on there was an Index definition created on SagaDataDocument that can't be done right now, becasue this class is no longer visible

**Comment by mookid8000** [comment]
Yeah ok, I can see why that's quite annoying – it's because you need access to the actual document type to be able to define an index on it, right?

If you're interested in making it public again, a PR is very welcome 🙂
